name: payment_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_statusbarcolor_ns: ^0.6.0
  font_awesome_flutter: ^10.8.0
  get: ^4.7.2
  http: ^1.3.0
  shared_preferences: ^2.5.2
  dio: ^5.8.0+1
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  flutter_animate: ^4.5.2
  flutter_svg: ^2.0.17
  flutter_html: ^3.0.0-beta.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Specify your asset paths here
  assets:
             
    - assets/               # Include all images in the asset folder